version: "3.9"

services:
  reusable_documents:
    container_name: reusable-documents
    build: .
    working_dir: /server
    command: uvicorn server.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    volumes:
      - .:/server
    ports:
      - "8000:8000"
    restart: on-failure
